### ISSUE TITLE
Sometimes I'm getting some garbage on the chat

### ISSUE THREAD

**Issue by Nerus87** [KeithGDR/chat-processor#4]
Platform: Linux
Version: 2.3.0
Used forward: CP_OnChatMessage
Result: sometimes I'm getting only colon `:` on the chat (this is nobody message and occurs automatically) or sometimes like on the screenshot:
![image](https://user-images.githubusercontent.com/3099926/184534312-f8d156bc-719a-47f0-8539-827a44abbe2a.png)

[Plugin code]
```
public Action CP_OnChatMessage(int& author, ArrayList recipients, char[] flagstring, char[] name, char[] message, bool& processcolors, bool& removecolors)
{
	if(!IsValidPlayer(author, true) || !sm_vipcontrol.BoolValue)
		return Plugin_Continue;

	if(IsAdmin(author))
	{
		Format(message, 256, "{%s}%s", AdminColor, message);
		
		return Plugin_Changed;
	}

	if(IsVip(author))
	{
		Format(message, 256, "{%s}%s", VipColor, message);

		return Plugin_Changed;
	}
	
	return Plugin_Changed; // <- maybe this is a problem and should be Plugin_Continue?
}
```

**Comment by KeithGDR** [comment]
I believe this might be caused by using an older version of Simple Chat Processor with an older version of Chat-Processor. I can't seem to replicate this issue though, tested with a few versions with both plugins loaded.

Either way, I updated the plugin to not load if Simple Chat Processor is running just in case.

**Comment by Nerus87** [comment]
I have only this plugin:
![image](https://user-images.githubusercontent.com/3099926/214972651-e4e12e54-a862-4868-b830-37d40626429e.png)
